version: "3.9"

name: bike-app-prod

services:
  db:
    container_name: bike-app-db-prod
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  server:
    container_name: bike-app-server-prod
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: npm run start
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    tty: true
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DATA_IMPORT_BUFFER_SIZE=${DATA_IMPORT_BUFFER_SIZE}
      - DISABLE_LOGGING_DURING_DATA_IMPORT=${DISABLE_LOGGING_DURING_DATA_IMPORT}
      - SERVER_PORT=${SERVER_PORT}
      - PAGINATION_MAX_LIMIT=${PAGINATION_MAX_LIMIT}

  client:
    container_name: bike-app-client-prod
    depends_on:
      - server
    ports:
      - 80:80
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

volumes:
  db_data_prod:
