version: '3.9'

name: bike-app-prod

services:
  db:
    container_name: bike-app-db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    container_name: bike-app-server
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm run start
    restart: unless-stopped
    ports:
      - 80:80
    tty: true
    environment:
      - DB_HOST=bike-app-db
      - NODE_ENV=${NODE_ENV}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DATA_IMPORT_BUFFER_SIZE=${DATA_IMPORT_BUFFER_SIZE}
      - DISABLE_LOGGING_DURING_DATA_IMPORT=${DISABLE_LOGGING_DURING_DATA_IMPORT}
      - SERVER_PORT=${SERVER_PORT}
      - PAGINATION_MAX_LIMIT=${PAGINATION_MAX_LIMIT}

volumes:
  db_data:
