version: '3.9'

services:
  db:
    container_name: bike-app-db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT_CONTAINER}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
